'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const workflow = read('.github/workflows/deploy-career-profile-admin-ui.yml');
const script = read('scripts/deployment/Invoke-NadiTrackApplicationRelease.ps1');
const moduleText = read('scripts/deployment/NadiTrackApplicationRelease.psm1');
const policy = JSON.parse(read('scripts/deployment/career-profile-admin-ui.approved.json'));
assert.match(script,/Expand-Archive[^\n]*\n\s*Initialize-ReleaseBuildSdk \$buildRoot/);
assert.match(script,/dotnet --list-sdks[\s\S]*dotnet --version[\s\S]*Assert-ReleaseBuildSdk/);
assert.match(moduleText,/rollForward='disable';allowPrerelease=\$false/);
assert.ok(!policy.files.some(f => /global\.json|web\.config|appsettings/i.test(f.name)));
assert.equal(policy.sourceSha, '6182e405ced08c24cf5f8738f1172c8df5197d3e');
assert.deepEqual(policy.files.map(f=>f.name), ['admin.html','admin.js','admin.css','career-admin.js','StackMeet.Api.dll']);
assert.match(workflow,/options: \[preflight, deploy\]/);
assert.match(workflow,/group: naditrack-production\s+cancel-in-progress: false/);
assert.equal((workflow.match(/environment: production/g)||[]).length,2);
assert.equal((workflow.match(/secrets.PROD_FTP_HOST/g)||[]).length,2);
assert.match(workflow,/ref: 6182e405ced08c24cf5f8738f1172c8df5197d3e/);
assert.match(workflow,/run-id: \$\{\{ inputs.preflight_run_id \}\}/);
assert.match(workflow,/if: \$\{\{ always\(\) \}\}/);
const deploy = workflow.slice(workflow.indexOf('\n  deploy:'));
assert.ok(!/setup-dotnet|dotnet |SourceDirectory|build -c/i.test(deploy), 'deploy must never rebuild');
assert.match(script,/Check-RemoteSource[\s\S]*Assert-DeployInterlocks/);
assert.match(script,/Assert-PreflightRun/);
assert.match(script,/Assert-ReleaseDirectory \(Join-Path \$fresh 'baseline'\)/);
assert.match(script,/Remove-Item -LiteralPath \$p -Force/,'never retain secret config content');
assert.match(script,/Read-RootNames/,'network errors must not be interpreted as absent files');
assert.match(script,/if\(\$Name -cne 'career-admin.js'\)/,'delete only newly added module during rollback');
assert.match(moduleText,/\$attempted=\$true[^\n]*\n\s*& \$Upload/);
assert.match(moduleText,/foreach\(\$f in \$r.files\)/,'rollback restores all members');
assert.match(moduleText,/Assert-LiveSnapshot \$r \(& \$Snapshot\)/,'verify whole prior set');
assert.match(moduleText,/SITE-STOPPED-NADITRACK-ONLY/);
assert.match(moduleText,/DEPLOY-CAREER-PROFILE-ADMIN-UI/);
assert.ok(!/Stop-WebAppPool|Restart-WebAppPool|Restart-Service|app_offline|SqlConnection|SqlCommand|Database\.Migrate|dotnet ef/.test(script+workflow), 'no pool, SQL or out-of-scope site operations');
assert.ok(!/SkipGate|SkipValidation|TestMode|MockMode/.test(script), 'entry point cannot bypass provenance');
console.log('Career Profile five-file release workflow guards passed.');
