'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const workflow = fs.readFileSync(path.join(root, '.github/workflows/deploy-career-profile-remediation.yml'), 'utf8');
const script = fs.readFileSync(path.join(root, 'scripts/deployment/Invoke-CareerProfileDllRelease.ps1'), 'utf8');
assert.match(workflow, /options: \[preflight, deploy\]/);
assert.match(workflow, /default: preflight/);
assert.match(workflow, /group: naditrack-production/);
assert.equal((workflow.match(/environment: production/g) || []).length, 2, 'both FTP jobs must bind production environment secrets');
assert.equal((workflow.match(/FTP_HOST: \$\{\{ secrets.PROD_FTP_HOST \}\}/g) || []).length, 2, 'environment secrets must be resolved in each job');
assert.match(workflow, /SourceRevisionId=\$env:SOURCE_SHA/);
assert.match(workflow, /git merge-base --is-ancestor \$env:SOURCE_SHA HEAD/);
assert.match(workflow, /Download exact preflight artifact without rebuilding/);
assert.match(workflow, /run-id: \$\{\{ inputs.preflight_run_id \}\}/);
assert.match(script, /lockedSource='1e2c0211aa00d39d55e444c42565c4111592fe78'/);
assert.match(script, /lockedLive='1533B551313FAAFF6B3A28985EC4FB5EB3FF3D4DEE04EEEEF82894479387D097'/);
assert.match(script, /POOL_CONFIRMATION -cne 'SITE-STOPPED'/);
assert.match(script, /DEPLOYMENT_CONFIRMATION -cne 'DEPLOY CAREER PROFILE DLL'/);
assert.match(script, /manifest\.files\[0\] -cne '\/StackMeet\.Api\.dll'/);
const upload = script.slice(script.indexOf('function UploadDll'), script.indexOf('function GitHub'));
assert.match(upload, /--upload-file/);
assert.match(upload, /\$port\/StackMeet\.Api\.dll/);
assert.ok(!/\$remote|ftp-create-dirs|DELE|app_offline/i.test(upload.replace(/#.*$/mg, '')), 'upload destination must be a single hard-coded DLL');
assert.match(script, /\$attempted=\$true\s+UploadDll \$target/, 'partial upload failures must enter rollback');
assert.match(script, /UploadDll \$backup/);
assert.match(script, /Hash \$check\) -cne \$lockedLive/);
assert.match(script, /VerifyConfig \$manifest\.protectedConfiguration/);
assert.match(script, /Retrieve \$remote \$local/);
assert.ok(!/SqlConnection|SqlCommand|ExecuteSql|Database\.Migrate|dotnet ef|dotnet run|StackerIdentityActivation/.test(script + workflow), 'release must not execute migrations, seeders or identity business operations');
assert.match(script, /Copy-Item -LiteralPath \(Join-Path \$scratch 'live\.dll'\) -Destination \(Join-Path \$baseline 'StackMeet\.Api\.dll'\)/, 'preflight must retain a durable rollback baseline');
assert.match(script, /resolved\.StartsWith\(\$runnerRoot/, 'recursive local cleanup must validate target containment');
console.log('Career profile DLL release safety guards passed.');
