const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const html = read("backend/StackMeet.Api/wwwroot/index.html");
const app = read("backend/StackMeet.Api/wwwroot/app.js");
const api = read("backend/StackMeet.Api/wwwroot/js/storage/CertificateTemplateApi.js");

assert.match(html, /certificateManagementPanel/);
assert.match(html, /Certificate Type/);
assert.match(html, /certificateTemplateFile/);
assert.match(html, /certificateRecipientRows/);
assert.match(html, /CertificateTemplateApi/);
assert.match(api, /Participation/);
assert.match(api, /Achievement/);
assert.match(api, /Official/);
assert.match(api, /ParticipantName/);
assert.match(api, /Placement/);
assert.match(api, /Result/);
assert.match(api, /application\/vnd\.openxmlformats-officedocument\.wordprocessingml\.document/);
assert.match(api, /8 \* 1024 \* 1024/);
assert.match(api, /authHeaders/);
assert.match(app, /certificateManagerSession/);
assert.match(app, /selectedCompetitionRole/);
assert.match(app, /certificateTemplateApi\.activate/);
assert.match(app, /certificateTemplateApi\.preview/);
assert.match(app, /Previous Version \/ Inactive/);
assert.match(app, /No PDF was rendered/);
assert.doesNotMatch(api, /PhysicalFile|ContentRootPath|StackTrace|web\.config/i);
assert.doesNotMatch(html + app + api, /Syncfusion|GemBox|pdf renderer/i);
console.log("Certificate management UI static tests passed.");
