const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const contracts = read("backend/StackMeet.Api/Services/CertificateRenderingContracts.cs");
const service = read("backend/StackMeet.Api/Services/CertificateGenerationService.cs");
const program = read("backend/StackMeet.Api/Program.cs");
const docs = read("backend/StackMeet.Api/Services/CertificateTemplateDocumentService.cs");
const html = read("backend/StackMeet.Api/wwwroot/index.html");
assert.match(contracts, /interface ICertificatePdfRenderer/);
assert.match(contracts, /CancellationToken/);
assert.match(service, /class CertificateGenerationService/);
assert.match(service, /PDF generation is not configured/);
assert.match(service, /IsActive/);
assert.match(service, /projections\.Resolve/);
assert.match(service, /documents\.Inspect/);
assert.match(service, /SafeFileName/);
assert.match(service, /ContentType/);
assert.match(program, /AddScoped<CertificateGenerationService>/);
assert.match(docs, /CertificatePlaceholderCatalogue\.SupportedTags/);
assert.match(html, /certificateGenerationCapability/);
assert.doesNotMatch(contracts + service, /Syncfusion\.|GemBox\.|LicenseKey|GEMBOX_LICENSE/i);
assert.doesNotMatch(read("backend/StackMeet.Api/StackMeet.Api.csproj"), /Syncfusion|GemBox/i);
console.log("Certificate generation architecture static tests passed.");
