const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const controller = read("backend/StackMeet.Api/Controllers/CompetitionAssetsController.cs");
const storage = read("backend/StackMeet.Api/Services/CompetitionAssetStorage.cs");
const model = read("backend/StackMeet.Api/Models/CompetitionAsset.cs");
const migration = read("backend/StackMeet.Api/Migrations/20260817060000_CompetitionAssetsPhase1.cs");
const designer = read("backend/StackMeet.Api/Migrations/20260817060000_CompetitionAssetsPhase1.Designer.cs");
const dto = read("backend/StackMeet.Api/Dtos/CompetitionAssetDtos.cs");
const assetClient = read("backend/StackMeet.Api/wwwroot/js/storage/CompetitionAssetApi.js");
const adminHtml = read("backend/StackMeet.Api/wwwroot/index.html");
const adminClient = read("backend/StackMeet.Api/wwwroot/app.js");
const program = read("backend/StackMeet.Api/Program.cs");
assert.match(model, /CompetitionId/);
assert.match(model, /Sha256/);
assert.match(storage, /CompetitionAssetsPath/);
assert.match(storage, /IncrementalHash\.CreateHash/);
assert.match(storage, /catch[\s\S]*File\.Exists\(path\)[\s\S]*File\.Delete\(path\)/);
assert.match(controller, /RequestSizeLimit\(5 \* 1024 \* 1024\)/);
assert.match(controller, /image\/png/);
assert.match(controller, /image\/jpeg/);
assert.match(controller, /image\/webp/);
assert.doesNotMatch(controller, /image\/svg/);
assert.match(controller, /CanManageCompetition/);
assert.match(controller, /PhysicalFile/);
assert.match(controller, /DetectFormat/);
assert.match(controller, /0xff && b\[1\] == 0xd8/);
assert.match(controller, /SequenceEqual\("RIFF"u8\)/);
assert.match(controller, /CacheControl = "no-cache"/);
assert.doesNotMatch(controller, /immutable/);
assert.match(controller, /CompetitionAssetUploaded/);
assert.match(controller, /CompetitionAssetReplaced/);
assert.match(controller, /CompetitionAssetRemoved/);
assert.match(controller, /Archived competitions cannot change branding/);
assert.match(migration, /CreateTable\([\s\S]*CompetitionAsset/);
assert.match(designer, /DbContext\(typeof\(StackMeetDbContext\)\)/);
assert.match(designer, /Migration\("20260817060000_CompetitionAssetsPhase1"\)/);
assert.match(program, /CompetitionAssetStorage/);
assert.match(dto, /PublicUrl/);
assert.match(assetClient, /FormData/);
assert.match(assetClient, /CompetitionAssetApi/);
assert.match(adminHtml, /competitionLogoFile/);
assert.match(adminHtml, /competitionBannerFile/);
assert.match(adminClient, /uploadCompetitionAsset/);
assert.match(adminClient, /removeCompetitionAsset/);
assert.match(adminClient, /asset\.publicUrl/);
console.log("Competition asset security and storage tests passed.");
