const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const stackers = read("backend/StackMeet.Api/Controllers/StackersController.cs");
const references = read("backend/StackMeet.Api/Services/CompetitionParticipantReferenceService.cs");
const competition = read("backend/StackMeet.Api/Controllers/CompetitionsController.cs");
const admin = read("backend/StackMeet.Api/Controllers/CompetitionAdminController.cs");
const app = read("backend/StackMeet.Api/wwwroot/app.js");
const html = read("backend/StackMeet.Api/wwwroot/index.html");
assert.match(stackers, /StackerCode cannot be changed after participant creation/);
assert.match(stackers, /CompetitionResults\.AnyAsync/);
assert.match(stackers, /references\.ContainsParticipant/);
assert.match(references, /JsonDocument\.Parse/);
assert.doesNotMatch(references, /json\.Contains/);
assert.match(competition, /CompetitionKey=value\.CompetitionCode/); // creation remains compatible
assert.doesNotMatch(competition, /item\.CompetitionCode=value\.CompetitionCode;\s*item\.CompetitionKey/);
assert.match(competition, /CompetitionAssets\.AnyAsync/);
assert.match(competition, /StateHasMeaningfulData/);
assert.match(admin, /CompetitionResults\.AnyAsync/);
assert.match(admin, /CompetitionAssets\.AnyAsync/);
assert.match(admin, /IsolationLevel\.Serializable/);
assert.match(admin, /CompetitionResults\.Where/);
assert.match(admin, /competition\.ResultsRevision\+\+/);
assert.match(admin, /ResetResultsOnly/);
assert.match(admin, /ResultsChanged/);
assert.match(app, /firstName: record\.firstName/);
assert.match(app, /lastName: record\.lastName/);
assert.doesNotMatch(app, /firstName: stacker\.name[\s\S]*lastName: "-"/);
assert.match(html, /stFirstName/);
assert.match(html, /stLastName/);
assert.match(html, /stWssaId/);
console.log("Core integrity V2 Phase B static tests passed.");
