const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const p = path.join(root, '.github', 'workflows', 'deploy-production.yml');
assert.ok(fs.existsSync(p), 'deploy-production.yml must exist');
const w = fs.readFileSync(p, 'utf8');
const has = (s, m) => assert.ok(w.includes(s), m || `missing: ${s}`);
const no = (r, m) => assert.ok(!r.test(w), m || `forbidden: ${r}`);

has('workflow_dispatch:');
no(/\n\s*(push|pull_request|schedule):\s*\n/i, 'production workflow must remain manual-only');
has('options: [preflight, ftp-readcheck, deploy, verify]');
has('contents: read');
has('group: naditrack-production');
has('cancel-in-progress: false');
has('APPROVED_LOCAL_DLL: backend/StackMeet.Api/bin/Release/net8.0/StackMeet.Api.dll');
has('APPROVED_REMOTE_PATH: /StackMeet.Api.dll');
has("REMOTE_PATH_CONFIRMED: 'true'");
has("if: ${{ inputs.operation == 'deploy' }}");
no(/inputs\.operation\s*==\s*'deploy'\s*&&\s*false/, 'confirmed FTP path must not retain the structural false gate');
no(/APPROVED_REMOTE_PATH:\s*__UNCONFIRMED__/, 'confirmed FTP path must not use the placeholder');
has("throw 'Remote FTP path confirmation gate failed'");
has('environment: production');
has('POOL-STOPPED');
has('DEPLOY StackMeet.Api.dll');
has('PRE_UPLOAD_BACKUP=PASS');
has('ROLLBACK_ATTEMPTED=True');
has('ROLLBACK_VERIFIED=False');
has('PRODUCTION_STATE=UNKNOWN');
has('DO NOT START THE POOL');

has('ftp_readcheck:');
has('name: FTP live DLL read-only check');
has("if: ${{ inputs.operation == 'ftp-readcheck' }}");
has('FTP_READ_ONLY_CHECK=PASS');
has('Read-only RETR failed');
has("'PRODUCTION_WRITES=0'");
const readStart = w.indexOf('  ftp_readcheck:');
const readEnd = w.indexOf('\n  deploy:', readStart);
assert.ok(readStart >= 0 && readEnd > readStart, 'read-only FTP job boundaries must be present');
const readOnly = w.slice(readStart, readEnd);
assert.ok(readOnly.includes('environment: production'), 'read-only FTP check must use production Environment');
assert.ok(readOnly.includes('APPROVED_REMOTE_PATH'), 'read-only FTP check must use approved remote path');
assert.ok(readOnly.includes('Get-FileHash'), 'read-only FTP check must verify the downloaded DLL hash');
assert.ok(!/--upload-file|\bStor\b|\bSTOR\b|Remove-Item|Rename-Item|Move-Item/i.test(readOnly), 'read-only FTP job must not contain remote-write primitives');
assert.ok(!/POOL-STOPPED|DEPLOY StackMeet\.Api\.dll/.test(readOnly), 'read-only FTP job must not require deployment interlocks or imply deployment');

has('enforce_expected_counts:');
has('default: false');
has('ENFORCE_COUNTS: ${{ inputs.enforce_expected_counts }}');
has('Production data count drift');
has('if($enforce){throw "$n count mismatch"}');
has('RESULTS_COUNT=$resultsCount');
has('STACKERS_COUNT=$stackersCount');
has('DOUBLES_COUNT=$doublesCount');
has('RELAYS_COUNT=$relaysCount');
has('COUNT_ENFORCEMENT=$enforce');
has('## Post-start verification');
const verifyStart = w.indexOf('  verify:');
assert.ok(verifyStart >= 0, 'verify job must be present');
const verifyOnly = w.slice(verifyStart);
assert.ok(verifyOnly.includes("'POST_START_HTTP_VALIDATION=PASS'"), 'verify must keep HTTP as a hard validation gate');
assert.ok(verifyOnly.includes("'PHASE3F_PUBLIC_API_SHAPE=PASS'"), 'verify must keep Phase 3F shape as a hard gate');
assert.ok(verifyOnly.includes("'PRIVACY_CHECK=PASS'"), 'verify must keep privacy as a hard gate');
assert.ok(verifyOnly.includes("'PRODUCTION_WRITES=0'"), 'verify must remain read only');
assert.ok(!/--upload-file|\bStor\b|\bSTOR\b|Remove-Item|Rename-Item|Move-Item/i.test(verifyOnly), 'verify job must not contain write primitives');

has('actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4');
has('actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4');
no(/uses:\s+actions\/(?:checkout|setup-dotnet)@v\d+/i, 'production actions must be pinned');

for (const r of [/\bdotnet\s+publish\b/i,/\bmsdeploy\b/i,/\bwebdeploy\b/i,/\brsync\b/i,/\bInvoke-Sqlcmd\b/i,/\bsqlcmd\b/i,/\bdotnet\s+ef\b/i,/\bdatabase\s+update\b/i]) no(r);
has("'(^|/)Migrations/'");
has("'\\.sql$'");
has("'(^|/)web\\.config$'");
has("'(^|/)appsettings(?:\\..+)?\\.json$'");

const storCalls = [...w.matchAll(/\bStor\s+([^\r\n;]+)/g)].map(m => m[1].trim());
assert.deepStrictEqual(storCalls, ['$dll $remote', '$backup $remote'], 'only approved DLL/rollback backup may be uploaded');

console.log('Production deployment workflow static guards passed.');
